server:
  port: 8888
spring:  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-shiro?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
mybatis:  type-aliases-package: com.wuheng.pojo
  mapper-locations: mapper/*.xml